language: shell

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
    - os: windows


env:
  global:
  - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
  - GRAVIS="$HOME/gravis"
  - JDK="adopt-openj9@1.8"

before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then chmod +x ./gradlew; fi
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

script: ./gradle build --console=plain --parallel

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.konan

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true
